name: "Seeker Report Exporter"
description: "Will use Seeker API to get given project vulnerabilites from Seeker and export options are Sarif and PDF."
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  log_level:
    description: Logging level
    default: DEBUG
    required: false
  url:
    description: Seeker server URL.
    required: false
  token:
    description: Seeker Access token to be used.
    required: false
  project:
    description: Seeker project, which vulnerability report will be exported.
    required: false
  version:
    description: Seeker project version, which vulnerability report will be exported.
    required: false
  codeLocationTypeKeys:
    description: Options are CUSTOMER_CODE_DIRECT_CALLS, CUSTOMER_CODE_NESTED_CALLS and THIRD_PARTY_CODE. All are returned by default. (Works only for Sarif -format output)
    required: false
  minSeverity:
    description: Options are INFORMATIVE, LOW, MEDIUM, HIGH, CRITICAL. All are returned by default.
    required: false
  onlySeekerVerified:
    description: Options are true or false. Will return only Seeker Verfied vulnerabilites.
    default: false
    required: false
  stacktrace:
    description: Options are true or false. If this is set to true, then possible stacktrace is added into the results.  (Works only for Sarif -format output)
    default: false
    required: false
  customTagNames:
    description: Comma separated list of tag names. If custom tag names are given, then only those vulnerabilities are returned which have given tags.  (Works only for Sarif -format output)
    required: false
  outputfile:
    description: Filename with path where it will be created, example /tmp/SeekerResults.sarif.json
    default: ${{github.workspace}}/SeekerResults.sarif.json
    required: false
  format:
    description: Select which format output will be. Options are sarif and pdf
    required: true
        
runs:
  using: composite
  steps:
    - if: ${{inputs.format == 'sarif'}}
      # Run the Python script
      run: |
        python3 ${{github.action_path}}/seekerResultsToSarif.py --log_level="${{inputs.log_level}}"" --outputFile="${{inputs.outputfile}}" --url="${{inputs.url}}" --token="${{inputs.token}}" --project="${{inputs.project}}" --version="${{inputs.version}}" --codeLocationTypeKeys="${{inputs.codeLocationTypeKeys}}" --minSeverity="${{inputs.minSeverity}}" --onlySeekerVerified="${{inputs.onlySeekerVerified}}" --stacktrace="${{inputs.stacktrace}}" --customTagNames="${{inputs.customTagNames}}"
      shell: bash
    - if: ${{inputs.format == 'pdf'}}
      run: |
        curl -s -o ${{inputs.outputfile}} -X 'GET' \
        '${{inputs.url}}/rest/api/latest/reports/export?language=en&sortField=severity&sortDir=DESC&projectKeys=${{inputs.project}}&projectVersions=${{inputs.version}}&minSeverity=${{inputs.minSeverity}}&onlySeekerVerified=${{inputs.onlySeekerVerified}}' \
        -H 'accept: application/pdf' \
        -H 'Authorization: ${{inputs.token}}' 
      shell: bash
